services:
  mysql:
    image: mysql:8.0
    container_name: cinema_mysql
    restart: always
    environment:
      MYSQL_DATABASE: cinema_db
      MYSQL_ROOT_PASSWORD: Zikph@m0907
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - cinema-network

  app:
    build: .
    container_name: cinema_backend
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - redis
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/cinema_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Zikph@m0907
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
    networks:
      - cinema-network

  redis:
    image: redis:alpine
    container_name: cinema_redis
    ports:
      - "6379:6379"
    networks:
      - cinema-network

volumes:
  mysql_data:

networks:
  cinema-network:
    driver: bridge
